apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: inbgyr49q-go-gitops
  description: This is GitOps manifest for inbgyr49q-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=inbgyr49q-go
    backstage.io/kubernetes-id: inbgyr49q-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: inbgyr49q-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:inbgyr49q-go
